#Be sure to change volumn location
#start:   docker-compose up -d
#stop:    docker-compse down

version: '1.0'

services:
    app:
        container_name: demo-app
        image: wyjared/se452-group10:latest
        env_file: ./.env
        ports:
            - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
        